### ISSUE TITLE
Disable author code block 

### ISSUE THREAD

**Issue by vysinsky** [dotblue/codesniffer-ruleset#4]

**Comment by vysinsky** [comment]
I think this is not needed.

1. We do not add this codeblock
2. Sometimes we can extract some class from soem library (eg PhpCrawler) and there we should keep whole 'licence' doc block

What's your opinion @vojtech-dobes?

**Comment by vojtech-dobes** [comment]
Totally agreed. Lets keep this rule as convention. We don't need to fight any IDE here.
