### ISSUE TITLE
Enable braces on same line as class/interface/method in case there is no body

### ISSUE THREAD

**Issue by vysinsky** [dotblue/codesniffer-ruleset#8]

**Comment by vysinsky** [comment]
When I am thinking about that. Is it really needed? I think we should not have empty interfaces/classes/methods.

**Comment by greeny** [comment]
What about abstract methods? And methods intended for overwriting in child class? (like `intitialize` etc.)

**Comment by vysinsky** [comment]
Abstract methods does not have body at all. And second case you describe are abstract methods :)

**Comment by vojtech-dobes** [comment]
I think there is room for these methods, @greeny hit the nail. Typical example is "abstract" method with default implementation, like `startup`.

```php
protected function startup() {}
```

So you don't need to write it all if you don't want to use it for hooking into some process. We could debate whether it's good architecture, but I am not sure right now, so I would rather allow this.

**Comment by vysinsky** [comment]
Background about why this issue was created:

Now sniffer complains about methods like:

```
public function foo() {}
```

Because standard is to have braces on the new lines. We have two options:

1. Edit existing sniff and enable inline braces for 'no body' methods
2. Remove the rule completely

**Comment by vysinsky** [comment]
I will go for option 2. We will not be strict in this. Do you agree @vojtech-dobes and @greeny ?

**Comment by vojtech-dobes** [comment]
Ideally we should enforce it except this specific case, but I wouldn't bother with it now I guess :). But if you know how to quickly implement it, be my guest :).

**Comment by vojtech-dobes** [comment]
:+1: :sparkles:

**Comment by vysinsky** [comment]
Reopening because PR fixed only empty methods. Not also empty classes.

**Comment by vysinsky** [comment]
Closed again by #36 :)
