### ISSUE TITLE
Check what are errors and what is bullshit

### ISSUE THREAD

**Issue by vysinsky** [dotblue/codesniffer-ruleset#9]
Check report here: https://gist.github.com/vysinsky/fa3cc5918b4d0c89bb1e

We can discuss here what is real erorr and what is bullshit.

/cc @vojtech-dobes, @greeny

**Comment by vysinsky** [comment]
Rules which are not covered by any issue yet **(MY OPINION)**.

1. End of line character is invalid; expected "\n" but found..... - KEEP
2. Opening brace must be the last content on the line - REMOVE
3. Closing brace must be on a line by itself - REMOVE
4. There must be a single space between the closing parenthesis the opening brace of a multi-line function declaration; found newline - HEH?
5. Whitespace found at end of line - KEEP
6. Usage of ELSE IF is discouraged; use ELSEIF instead - KEEP
7. Arguments with default values must be at the end of the argument list - KEEP
8. Each class must be in a namespace of at least one level (a top-level vendor name) - KEEP
9. Opening parenthesis of a multi-line function call must be the last content on the line - REMOVE
10. Only one argument is allowed per line in a multi-line function call - KEEP
11. Closing parenthesis of a multi-line function call must be on a line by itself - REMOVE
12. There must be a comment when fall-through is intentional in a non-empty case body - KEEP
13. Property name "$__domainRepository" should not be prefixed with an underscore to indicate visibility - KEEP
14. Expected 1 newline after opening brace; 0 found - IMPROVE - enable comments on the same line
15. Visibility must be declared on property - KEEP

Let's discuss :)

**Comment by vojtech-dobes** [comment]
Ad interface & visibility - we shouldn't forbid protected I think, because it's valid. We should only disallow `public`.

**Comment by vysinsky** [comment]
Closing this. As we'll find some issue on code we can discuss it separately.

**Comment by vojtech-dobes** [comment]
:+1:
